/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryChart: typeof import('./components/admin/CategoryChart.vue')['default']
    ChatInterface: typeof import('./components/customer/ChatInterface.vue')['default']
    ChatPanel: typeof import('./components/agent/ChatPanel.vue')['default']
    CustomerPanel: typeof import('./components/agent/CustomerPanel.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    FaultReportDialog: typeof import('./components/agent/FaultReportDialog.vue')['default']
    HomeScreen: typeof import('./components/customer/HomeScreen.vue')['default']
    IssueList: typeof import('./components/admin/IssueList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsGrid: typeof import('./components/admin/StatsGrid.vue')['default']
    TaskList: typeof import('./components/agent/TaskList.vue')['default']
    TrendChart: typeof import('./components/admin/TrendChart.vue')['default']
  }
}
