/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInterface: typeof import('./components/customer/ChatInterface.vue')['default']
    ChatPanel: typeof import('./components/agent/ChatPanel.vue')['default']
    CustomerPanel: typeof import('./components/agent/CustomerPanel.vue')['default']
    FaultReportDialog: typeof import('./components/agent/FaultReportDialog.vue')['default']
    HomeScreen: typeof import('./components/customer/HomeScreen.vue')['default']
    IssueList: typeof import('./components/admin/IssueList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsGrid: typeof import('./components/admin/StatsGrid.vue')['default']
    TaskList: typeof import('./components/agent/TaskList.vue')['default']
    TrendChart: typeof import('./components/admin/TrendChart.vue')['default']
  }
}
